### ISSUE TITLE
Event for Mouse "Down and Out"?

### ISSUE THREAD

**Issue by proyb6** [craftyjs/Crafty#1005]
If I have a use case that only respond when mouse "down and out" rather than just detecting "mouseout" of a sprite, I think this feature is useful to have.

```
Crafty.e("2D, DOM, Mouse, Paintbox").attr({x:0, y:0)
.bind('MouseDown', function(e){this.sprite(28,0);mouseKey("take")})
.bind('MouseUp', function(e){this.sprite(0,0);mouseKey("release")})
.bind('MouseOut', function(e){
//Mouse down and out?
})
```

**Comment by 200sc** [comment]
You can write such a case yourself easily and I don't think it's worth being in the crafty library itself, personally.

**Comment by 200sc** [comment]
Also, this is essentially what the Dragging component is.

**Comment by proyb6** [comment]
I tried Dragging that will calculated every movement which isn't applicable as my use case is similar to e.g. 2 html `<button>` a user will mouse down and hold button on button 1, when hover out, the button 1 will reset to default state and button 2 will not respond to any mouse event until the mouse button is release.

For this I use a temporary variable as a workaround to store the unique name of the sprite and the mouse down event will only respond to that unique name. I hope my explanation isn't confusing, but MouseDownOut and DragDownOut are both useful if we could avoid using temporary variable.

**Comment by 200sc** [comment]
Look, your binding should be to MouseOut and then should check the mouse event data you're passed to see if a button is down. You can google this stuff. The crafty documentation tells you that it's sending you a MouseEvent. You shouldn't need any new variables, you're already provided all the information you need. I'd recommend you look around for alternate solutions to your problems prior to believing your issue to be a concern with the engine itself-- Crafty isn't perfect, but this board, as far as I know, is meant for suggestions to improve the engine and you've been using it to get debugging help on generic javascript concerns.

Your button concerns don't even require what you're asking for. Just bind to Click instead of mouseUp for your button responses

**Comment by proyb6** [comment]
I have done that check on button down before.

On other hand, I found there is a bug, the mouse event has 2 duplicated
isTrusted, I don't know why,

**Comment by mucaho** [comment]
@proyb6 
There is a new component named [`MouseDrag`](http://craftyjs.com/api/MouseDrag.html) which provides drag & drop events without actually moving the entity. Does that suit your use-case?

**Comment by starwed** [comment]
AFAICT this is now handled by Crafty, so closing.  But reopen if there's a specific bug!
