### ISSUE TITLE
Demo falls through the floor

### ISSUE THREAD

**Issue by naasking** [craftyjs/Crafty#1006]
Your "first game" demo block doesn't respect the floor:

http://jsfiddle.net/kevinsimper/2nBLb/2/?utm_source=website&utm_medium=embed&utm_campaign=2nBLb

If you hold down the up key for about 2 seconds, it gives a little hop then stays there. When you release the key, the block starts slowly falling through the floor. Tried in IE11, Firefox and Chrome on Windows.

The wording of the tutorial implies this isn't the expected behaviour, since it's supposed to be a floor.

**Comment by 200sc** [comment]
I believe this is from a change to what range of values fourway takes-- now it's pixels per second, or something like that? Probably want to update it from 4 to something like 400.

[Example with 400](http://jsfiddle.net/2nBLb/523/)

**Comment by naasking** [comment]
Still happens. Press the up arrow key until the box hits the floor again, then when you let go it falls right through the floor.

**Comment by 200sc** [comment]
Right, I see what you mean. In my projects finicky things with fourway and gravity like this have always pushed me to write my own versions. It's worth looking into gravity's code to see why it's check is failing on keyup.

**Comment by mucaho** [comment]
Thanks for reporting!

The problem was `Fourway` was never meant to be used with `Gravity`, that's what `Twoway` is for. This was probably a typo by the author and should have been fixed via craftyjs/craftyjs.github.com@4c2f35189bbca210e135a73b8bba204a2a15a826.

I have updated the site with the fix that replaces `Fourway` with `Twoway` (craftyjs/craftyjs.github.com@e5c4f916d11139592550bd5ea3f8d0070558afbb), as well as updated the speed values to match the new crafty version (craftyjs/craftyjs.github.com@529be6ec2202c14e56c77908640f9fbbb2280b59).

I hope this resolves the issue now, if not, please reopen this issue.

**Comment by naasking** [comment]
The demo does work as expected now, but I don't see anything in the Fourway, Gravity or Twoway docs that suggest Fourway wouldn't work with Gravity (or it only working with Twoway). If mixing Fourway with Gravity still exhibits the same behaviour, that still seems like a bug.

**Comment by mucaho** [comment]
> I don't see anything in the Fourway, Gravity or Twoway docs that suggest Fourway wouldn't work with Gravity (or it only working with Twoway)

Good point! That should be reflected in documentation (#1008).

> If mixing Fourway with Gravity still exhibits the same behaviour, that still seems like a bug.

Does it really make sense mixing Fourway with Gravity?

In a side-scrolling platformer you can go either left, right or jump (you will also fall automatically due to gravity after jumping). That's what Twoway and Gravity are used for.

In a top-down perspective game you want to move in 8 directions. That's what Fourway is used for. Gravity would then affect the player's z position (that's the rendering order in an orthogonal projection). However, Gravity currently only affects the player's y position (there are some ideas to change that for isometric projection).

Is there some other use-case for gravity in a top-down game I'm missing? These controls are made for the most common use-cases. If you want a more specific control mechanism, you can roll your own (e.g. on top of the [Motion](http://craftyjs.com/api/Motion.html) system). Creating your own components is even encouraged, if you make something which could come in handy for others, share it with us please!

**Comment by naasking** [comment]
I don't have a use case, it just seemed odd that it would evade the collision detection in this one case. It's obviously a bug, probably an off-by-one scenario where a displacement is applied on key up for one frame before checking for collisions, when it should be the other way around.

It's certainly not an important bug to fix given your explanation, so #1008 certainly suffices as a fix.
