### ISSUE TITLE
Viewport's mouselook conflicts with other Mouse entities

### ISSUE THREAD

**Issue by naasking** [craftyjs/Crafty#1013]
Here's the sample showing the problem: https://jsfiddle.net/8va2w9r4/

This might be a little tricky to explain. Click and hold to grab the viewport right next to the shape, then quickly move the mouse over the shape. While you're over the shape, the viewport stops panning with the mouse movement, and if you let go of the mouse button and move the mouse off the shape, the viewport still pans as if you had the button pressed. You can click anywhere on the background to release of course.

May not seem like a big deal, but I've actually gotten into scenarios with fast mouse dragging where Crafty thinks I grabbed the viewport to pan while the mouse is over a shape. So everytime I move off the shape, the shape ends up back under the mouse so I can _never_ release the viewport pan behaviour.

To get out of it, I have to move the mouse super-quick off the shape and click before it follows and ends up under the mouse again. I hope that's clear.

I have no opinion on whether all mouse move events should be respected while over the shape while in mouselook mode (they currently aren't), but I definitely think mouseup should be handled as if you weren't over the shape.

**Comment by 200sc** [comment]
(This happens even without Draggable, but just with Mouse on the red cube).

So the mouseUp event is getting consumed by the cube and isn't being passed down back to the viewport. Is it possible to always pass down mouseUp events to the viewport, assuming mouselook is the only thing the viewport will care about with respect to mouse events?

It looks like the viewport is using [Crafty.mouseObjs++](https://github.com/craftyjs/Crafty/blob/develop/src/graphics/viewport.js#L448) to tell Crafty that it wants to receive events.

Mouse events are handled [here](https://github.com/craftyjs/Crafty/blob/develop/src/controls/inputs.js#L159), and mouselook is already special cased out-- this would be a solution given the current architecture, but it might be nice to pull out the active boolean mouselook uses to ignore this call (when it isn't active) and expose it to the mouse event handler?

```
if (closest) {
            //click must mousedown and out on tile
            if (type === "mousedown") {
                closest.trigger("MouseDown", e);
            } else if (type === "mouseup") {
                Crafty.viewport.mouselook('stop');
                closest.trigger("MouseUp", e);
            } else if (type == "dblclick") {
                closest.trigger("DoubleClick", e);
            } else if (type == "click") {
                closest.trigger("Click", e);
            } else if (type === "mousemove") {
            ...
```

**Comment by starwed** [comment]
It seems to me this is probably a general problem: an entity or system should be able to acquire a lock on pointer behavior, and get to decide whether it will stop propagation of the event to other entities or not.

**Comment by mucaho** [comment]
Well, all mouse events are routed through a single codeblock - [Crafty.mouseDispatch](https://github.com/craftyjs/Crafty/blob/a0aad4529b84b924b54c4d90666f5dd7bcfb544b/src/controls/inputs.js#L132-L212). That's good, because we can fix the implementation there (as Sythe2oO also noted).

---

> an entity or system should be able to acquire a lock on pointer behavior, and get to decide whether it will stop propagation of the event to other entities or not.

Going further, I would also suggest to make the base `Crafty.stage` a mouse-enabled entity. So any mouse events that don't go to any other mouse-enabled entities would go to this background entity per default. You could then listen for these events. (Viewport's mouselook could be changed to listen to these events on the background).
This is particularly helpful, because the two available alternatives (that I know of) for listening to mouse events on the background are a bit lackluster:
- Having an explicit background entity that moves & scales according to viewport changes has a (small) performance impact.
- If you listen to mouse events on the DOM element `Crafty.addEvent(this, Crafty.stage.elem, "mousedown", myMouseHandler)` you won't know if the events were dispatched by `Crafty.mouseDispatch` to an entity already or not (so you actually won't know if the background was clicked or not).
