### ISSUE TITLE
Animation seems to be a bit rough even with a single circle on mobile devices.

### ISSUE THREAD

**Issue by 9itish** [craftyjs/Crafty#1050]
First of all, I really like Crafty. It is super easy to learn and use. I have been playing with this library for some time now and even though everything works as expected there is a noticeable lag. Please take a look at [this fiddle](https://jsfiddle.net/8ugqxz3z/2/) to see what I mean.

Am I unknowingly using the library sub-optimally? This is my complete animation code:

```
$(document).ready(function () {
        var gWidth = window.innerWidth;
        var gHeight = window.innerHeight;
        $("#game, canvas").css({width: gWidth, height: gHeight});

        Crafty.init(gWidth, gHeight, document.getElementById('game'));     

        var myCircle = Crafty.e("2D, Canvas, Color, Collision").attr({
            x: gWidth/2
            , y: gHeight/2
            , w: 0.04*gHeight
            , h: 0.04*gHeight
            , r: 0.02*gHeight
            , color: 'brown'
            , xDirection: 0.005*gWidth
            , yDirection: 0.005*gHeight
        }).bind("EnterFrame", function (eventData) {
            this.x += this.xDirection;
            this.y += this.yDirection;
            if (this.x < 0) this.xDirection *= -1;
            if (this.y < 0) this.yDirection *= -1;
            if (this.x > (0.96*gWidth)) this.xDirection *= -1;
            if (this.y > (0.96*gHeight)) this.yDirection *= -1;
        });     
    });`
```

The animation has a slight lag even on PC. Is there something that I can do about it?

**Comment by starwed** [comment]
> The animation has a slight lag even on PC. Is there something that I can do about it?

Just to check,  do you see this lag when running the game directly?  (As opposed to on jsfiddle.)  Have you tried doing any direct profiling?  (Most browsers now have a built-in tool that can let you see what the bottleneck is.)

I can't really reproduce the issue locally, but here are some Crafty tips that might help: 
- You can switch to using the `Motion` component, and then change the [steptype](http://craftyjs.com/api/Crafty-timer.html) that Crafty uses to "variable".   (The default steptype is fixed, in which each "EnterFrame" event represents the same amount of time -- without switching to "Motion" or otherwise taking into account the actual timestep, your velocity calculations above would be off.)  You can also reduce the target FPS to something lower, depending on what your game needs.  This can result it much smoother animations.

```
Crafty.init(gWidth, gHeight, document.getElementById('game'));
Crafty.timer.FPS(30); // the default is 50
Crafty.timer.steptype("variable");

// ...

var myCircle = Crafty.e("2D, Canvas, Color, Circle, Motion").attr({
                x: gWidth/2
                , y: gHeight/2
                , w: 0.04*gHeight
                , h: 0.04*gHeight
                , radius: 0.02*gHeight
                , color: 'brown'
                , vx: 0.2*gWidth
                , vy: 0.2*gHeight
            }).bind("EnterFrame", function (eventData) {
                if (this.x < 0) this.vx *= -1;
                if (this.y < 0) this.vy *= -1;
                if (this.x > (0.96*gWidth)) this.vx *= -1;
                if (this.y > (0.96*gHeight)) this.vy *= -1;
            });  
```
- You could also try rendering the circle to an image, and then using that image.  That can [be faster](http://stackoverflow.com/questions/12254415/canvas-arc-vs-drawimage) than using `arc`, though not by a huge amount, so it's probably not what you're seeing here?

**Comment by 9itish** [comment]
Hey, starwed. Thanks for responding so quickly and for all those suggestions. :) I have created two different demos. 

[The first one](http://jsfiddle.net/4fWt5/118/) does not use any libraries and  [the second one](https://jsfiddle.net/8ugqxz3z/5/) uses Craftyjs. There is a slightly noticeable jerkiness in the second case when you compare both these demos. Do you notice the same?

**Comment by 9itish** [comment]
I measured the framerate on mobile devices as well as on PC. On Chrome, the framerate was 60fps, while on mobile in was between 27 and 35 fps.  Actually, I am trying to develop android games using Ionic and they will be running in a webview. :)

**Comment by 200sc** [comment]
I don't see any frame rate drop on my android, but I'd generally avoid doing anything that required redefining a draw call or adding draw logic to the draw binding in crafty. Crafty is useful for games built on sprite animations, but it's not particularly focused on performance from my experience. That said, I didn't have any issues performance wise with crafty until I had to deal with drawing thousands of tiles.

**Comment by 9itish** [comment]
@Sythe2o0 The animation runs smoothly on Chrome for android. It just lags when running inside the inbuilt android browser.

**Comment by 9itish** [comment]
After some testing, it seems like the lag appears only on android version 4.4 and below.  So, it is not the library but the android webview which is at fault. :)
