### ISSUE TITLE
Fix disabled webdriver cloud tests

### ISSUE THREAD

**Issue by starwed** [craftyjs/Crafty#1079]
We have a small set of tests that run via webdriver, and compare Crafty's actual rendering to a set of expected screenshots.  These get run in multiple browsers on open-sauce through webdriverio.

The existing tests can check:
- That multiway works as expected (this covers keyboard input and basic 2D placement)
- That a Color element produces the expected color for Canvas, DOM, and WebGL.

Currently the following sets of tests are disabled:
### All  WebGL tests

 SauceLabs doesn't provide WebGL support. The only possible resolutions here are to wait until they do, or switch to a similar provider like BrowserStack.

### All mobile tests

It's very hard to get the mobile screenshots to compare to the existing shots.  Browser/phone chrome and varying aspect ratios cause a lot of problems.  Previously there was some attempt to measure the discrepancy and manually compensate, but this seems to require separate settings for every mobile version, which isn't very maintainable.  Resolution here would be to either compare something other than an exact screenshot, or figure out a more adaptable way to get the screenshots in the first place.

### The multiway test in Firefox

The test driver for Firefox seemed to be redirecting keyboard input to the urlbar.  This might be resolved by upgrading the version of selenium we use?   There's a supposed profile setting that can help here (`focusmanager.testmode:true`), but either I didn't correctly get it set to true, or it didn't resolve the issue.

**Comment by mucaho** [comment]
Yeah, it was quite tricky to get webdriver working again and it's always a trial & error process when trying to test on newer browsers or when older platforms become deprecated.

I hope I've simplified our test code now over this week's commits. 
Mobile browsers are a nightmare to get good screenshots from, so I have removed them from webdriver testing (at least for now I don't know of a more appropriate solution). Edge actually supports WebGL, which is nice.

In future if something breaks or we want to add a new browser, we can look at [sauce lab's platform configurator](https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/) and make appropriate changes in the [tests/test-browsers.json](https://github.com/craftyjs/Crafty/blob/develop/tests/test-browsers.json) file. Notice how there are custom properties like `syntheticMouseEvent: true` now. The test code will then send these synthetic events to the browser, instead of trying to fire them natively.

There is a way to test new changes to webdriver tests without impacting our `testing` build status. Set the `SAUCE_BRANCH=webdriver-test` and replace the opensauce credentials with these:
```
  # OpenSauce credentials: for webdriver-test branch
  - secure: PaYu4SsAG7cgO/m9BtGTMhsvWjQxSsogMDfOuuk9tLt7MFZF7krmyV8ACsMy+HQ0H4yyAeBBSUJHf4N7dXwLhqsrv+lyohKcu+GUv2R+10WIDCzMlO76Y32fBoJtI6kZjrG51oW2mtjb4prhSr9unZP4V5nViDuM44MMCRu3kxc=
  - secure: Y3UvNGsD1F0/L62+GX9ikztZ26V9JZ6HuhNZoz0AAy9UMQCOwHWtaDQQvnOlm6i5XEMF69XQfhpLGKUJlrJakEPSy3LR3cbX4+JanwIZRYoevrOgnkAscfaNBO5e+XFVT4SQvqmYGAu0r5ryStbrzmuyrNmx/lateUoNVbgR2MM=
```
Now when you push to upstream (the craftyjs) repo all sauce tests will run. You can check the status on my [`mucaho-test` sauce labs subaccount](https://saucelabs.com/open_sauce/user/mucaho-test). e.g. [see the latest build I tested all my changes with](https://saucelabs.com/beta/builds/1fc5743c632d4f87b8bf3e02bced24b0).

We can add additional browsers that will run on the local machine, but I'd like to add some more tests before doing so, as these will require considerable amount of storage space. `electron` is like phantomjs based on webkit, but is more heavy and supports WebGL tests. `slimer` needs a separately (!) installed firefox, but supports WebGL tests and covers our tests for gecko-based browsers.
