### ISSUE TITLE
MouseDrag not working

### ISSUE THREAD

**Issue by ihabZhaika** [craftyjs/Crafty#1084]
Hi,
i am trying to use the mouse drag feature 
http://craftyjs.com/api/MouseDrag.html

This is the code i tried to use the feature on :
https://jsfiddle.net/yL3v48r6/62/

after adding the required attributes , still the red paddle still not moving by the drag event

**Comment by 200sc** [comment]
The component you are looking for is [Draggable.](https://github.com/craftyjs/Crafty/blob/develop/src/controls/controls.js#L11) Require that instead of MouseDrag: [fiddle](https://jsfiddle.net/yL3v48r6/64/)

Also, .startDrag() is used to simulate a drag starting, not to enable functionality.

anti-tl;dr-  MouseDrag just gives the user the ability to bind a given function to the Dragging event. It also offers simulation of starting and stopping drags through the .startDrag() and .stopDrag() functions. A common use case of MouseDrag is for an entity to follow the mouse's movement on dragging. Draggable exposes this functionality on top of MouseDrag.

**Comment by ihabZhaika** [comment]
hi,
great , you are correct

**Comment by ihabZhaika** [comment]
Hi,
is there any callback that triggered when the drag is over ?

**Comment by starwed** [comment]
The `StopDrag` event is supposed to fire [according to the docs](http://craftyjs.com/api/MouseDrag.html), though I haven't used it before.

**Comment by ihabZhaika** [comment]
Thx,
demo code for who wants
https://jsfiddle.net/yL3v48r6/66/
