### ISSUE TITLE
Fourway component should allow setting normalize and other options

### ISSUE THREAD

**Issue by TommyDong1998** [craftyjs/Crafty#1092]
player.fourway(200)
When moving sideways in fourway. It does not actually move 200px a second distance.
It moves 200px horizontally and 200px vertically. 
In order to move 200px distance it should be.
200px * sqrt(2)/2 horizontally and vertically.
It is possibke to do it manually    with bind and change speed but I think it should be incorporated.

**Comment by starwed** [comment]
The underlying component [Multiway](http://craftyjs.com/api/Multiway.html) allows this -- you can set the `normalize` option to `true`, and it will do as you suggest.  Just call it with the [same keybindings](https://github.com/craftyjs/Crafty/blob/6998fc9e5dd81ac253023ad85232404c696484e8/src/controls/controls.js#L583-L594) that Fourway uses, and the additional options argument.

We should make it so that Fourway lets you pass in the options more easily, so I'll edit the title of this issue accordingly.

**Comment by TommyDong1998** [comment]
ahh. I didnt see that. thanks for putting links.
