### ISSUE TITLE
Question: Why linkinput and unlinkinput don't return component? And what is the best way to bind multiple controls to entity?

### ISSUE THREAD

**Issue by Askadar** [craftyjs/Crafty#1102]
Is there a reason for that? 
The problem is - I wanted to bind multiple controls to entity, and obviously tried linking them chained like so:

    .linkInput('TriggerInputDown', 'UP', a => console.log(a))
    .linkInput('TriggerInputDown', 'DOWN', a => console.log(a));
I already saw question about movement, but this question still stands in cases like binding certain player abilities for example. 
So the bonus question is; what is the best way to bind multiple controls to entity?
Also, I've done quick and dirty edit of local version to return component on linking input and everything works, so  I can't understand why it's done the way it is.

**Comment by starwed** [comment]
>Is there a reason for that?

> .. I've done quick and dirty edit of local version to return component on linking input and everything works

Nope, this is a simple oversight -- they should return the entity.  If your local version works, feel free to open a PR with just those changes.  (No worries if that's not practical, I'll make sure it's fixed by the next release.)

>So the bonus question is; what is the best way to bind multiple controls to entity?

Two separate calls to linkInput (as in your example) makes sense to me.
