### ISSUE TITLE
Ideas and bugs for Control System

### ISSUE THREAD

**Issue by mucaho** [craftyjs/Crafty#1128]
# Bug 1
DPads and Triggers do not get cleaned up when entity is destroyed. They linger in Controls System even if nothing is using them.

Some ideas:
* Reference count of whatever uses them, if triggers / dpads are meant to be used by mulitple objects
* Otherwise, let the object dispose of the trigger once it no longer uses it (e.g. in entity / system `remove` method)

# Bug 2 
DPad is incorrectly computing active directions due to rounding errors when multiple directions are active.  Happens when you use diagonal directions. 
To reproduce, replace [these lines](https://github.com/craftyjs/Crafty/blob/0bdae16933e0e8e8d893ec4a725eb355bd4e6a73/tests/unit/controls/controls.js#L496-L501) with
```js
    // pressing two keys of opposite directions cancels out all movement
    keysDown(Crafty.keys.NUMPAD_2, Crafty.keys.NUMPAD_8);
    Crafty.timer.simulateFrames(1);
    _.strictEqual(e._vx, 0, "vx = 0 when NUMPAD_8 & NUMPAD_2 pressed");
    _.strictEqual(e._vy, 0, "vy = 0 when NUMPAD_8 & NUMPAD_2 pressed");
    keysDown(Crafty.keys.NUMPAD_7, Crafty.keys.NUMPAD_3);
    Crafty.timer.simulateFrames(1);
    _.strictEqual(e._vx, 0, "vx = 0 when NUMPAD_8 & NUMPAD_2 & NUMPAD_7 & NUMPAD_3 pressed");
    _.strictEqual(e._vy, 0, "vy = 0 when NUMPAD_8 & NUMPAD_2 & NUMPAD_7 & NUMPAD_3 pressed");
    keysUp(Crafty.keys.NUMPAD_7, Crafty.keys.NUMPAD_3);
    keysUp(Crafty.keys.NUMPAD_2, Crafty.keys.NUMPAD_8);
```

Some ideas:
* Rounding of values if there are close to 0 or 1, maybe something similar to [what we do on rotation](https://github.com/craftyjs/Crafty/blob/5cb1f3a5ad650354c915fe0d3c9eab5c3b964aa2/src/spatial/2d.js#L409-L410). From my initial debugging that should probably happen [after adding up all active directions and before normalization](https://github.com/craftyjs/Crafty/blob/0bdae16933e0e8e8d893ec4a725eb355bd4e6a73/src/controls/controls-system.js#L293), as even the tiniest number gets normalized to 1, if the other axis is equal 0.
 * [The e6 workaround](https://github.com/craftyjs/Crafty/pull/931#r46105529) that was used in an older PR. It wasn't there just for fun! :)

# Idea

[Reposting](https://github.com/craftyjs/Crafty/pull/1051#issuecomment-298742576) for visibility:
Deprecate `linkInput` and `unlinkInput`. Trigger and bind to events with the triggerName / dpadName as the eventName instead.

**Comment by starwed** [comment]
>DPads and Triggers do not get cleaned up when entity is destroyed. They linger in Controls System even if nothing is using them.

I think that when an entity creates a control, it should probably be responsible for cleaning it up when not needed -- so e.g. Multiway should be destroying the dpads.

>Deprecate linkInput and unlinkInput. Trigger and bind to events with the triggerName / dpadName as the eventName instead.

The idea here is that these are just convenience methods with a small optimization; since the control name was added as a property of the event argument, it made binding directly to the event feel a bit annoying, since you had to filter out the ones you don't care about.  

The alternative you suggest is to have custom control events with a documented naming convention?  So that if your dpad was `"MyDpad"`, you'd bind to `"DirectionalInputMyDpad"`?

I'm not especially opposed to that, but I think that in most ways that's pretty much the same; you'd probably still want a helper method so that you don't have to check if you got the convention correct.  

I guess the main functional difference is that with the existing system, you could theoretically add a global listener for `"DirectionalInput` that then did something based on the control name.  I can't actually think of a use case for that, though!

**Comment by mucaho** [comment]
> I think that when an entity creates a control, it should probably be responsible for cleaning it up when not needed

Agreed, PR coming up.

> So that if your dpad was "MyDpad", you'd bind to "DirectionalInputMyDpad"? .. you'd probably still want a helper method so that you don't have to check if you got the convention correct.

I was thinking more of triggering a "MyDpad" event instead. Makes sense in that case, however, for TriggerInput you'd then indeed need a convention for event names, like "MyTriggerUp" and "MyTriggerDown".

> The idea here is that these are just convenience methods

Yep, it's just a minor aesthetics thing, compare
```js
.linkInput("TriggerInputDown", "BlushTrigger", function(){this.color('pink');});
```
with
```js
.bind("BlushTriggerDown", function(){this.color('pink');});
```
Feels a tad more idiomatic & natural to me.

Additionally it's probably a little bit faster to trigger "BlushTriggerDown" instead of "TriggerInputDown", since for the latter each callback handler is called and has to check whether it was the intended target.

It's not a big deal either way, just wanted to bring it to your attention. (Another option would be to trigger "BlushTriggerDown" in addition to "TriggerInputDown", so you could choose according to your preference.)

**Comment by mucaho** [comment]
fixed by referenced PRs
