### ISSUE TITLE
Does it have WebGL support? If so does it support WebGL 2.0?

### ISSUE THREAD

**Issue by vickylance** [craftyjs/Crafty#1152]
Hi, Just out of curiosity the official website mentioned Canvas and DOM? So I was wondering does it support WebGL and if it does Does it support WebGL 2.0 rendering.

Thanks.

**Comment by starwed** [comment]
We support WebGL, but not yet WebGL 2.0.  I could have sworn that had been added to the landing page, but apparently not!

You use it by adding the [`WebGL`](http://craftyjs.com/api/WebGL.html) component instead of `DOM` or `Canvas`.  You can also [override](http://craftyjs.com/api/Crafty-WebGLShader.html) parts of the default implementation if you want to do something more advanced.

There are some nice features in 20, but it's [not yet widely supported](http://caniuse.com/#feat=webgl2).

**Comment by vickylance** [comment]
Hi thanks for the info. It's good to see the WebGL support :)
Will give it a try.

Thanks.
