### ISSUE TITLE
Can I use the name Crafty for another project ?

### ISSUE THREAD

**Issue by onigoetz** [craftyjs/Crafty#1158]
Hello @starwed and team.

I am going to release an Open Source project soon in the company I work for (https://github.com/swissquote/) The thing is that the internal name of the project is Crafty.

The project is a tool that helps configuring Webpack, Rollup, Babel, TypeScript, PostCSS and many other frontend tools together. So it's a completely different space than your project, but it's also in JavaScript.

So to my question: Is it okay for you if we use the same name for our project ? The npm name would be `@swissquote/crafty` so we wouldn't be too close of your npm package name.

It would be no problem for us to add a link to the documentation like "Looking for the Game Engine? it's this way".

Thanks in advance.

**Comment by starwed** [comment]
Hi!

I guess my instinct is that it would be better if your team could somehow adopt a different name, since it could be a bit confusing in both directions, especially when using they will both have packages hosted on npm.

But consider that more advice than a demand.  :)  Like you say, the two projects are in different spaces, so as long as the package names etc all make the distinction, it will hopefully work out ok in practice.

I guess I'll tag @louisstow as the original author of Crafty, on the off chance that he has anything to add.  But he hasn't been involved in a few years, so I wouldn't really expect a response.
