### ISSUE TITLE
There is a background buffer bug when painting on top of another

### ISSUE THREAD

**Issue by demarcop** [craftyjs/Crafty#1176]
There is a bug where a buffer is overwriting the existing drawing and replacing it with background? color.

This is very odd because it's minimal if I pick certain numbers, in my case 80, and if I pick 81 it becomes large again.   Very strange for me.

Anyway I created a jsfiddle to demonstrate this problem.   The 80, is on line 75
Thanks

https://jsfiddle.net/juLhj3sc/10/

**Comment by starwed** [comment]
It's a little hard for me to tell what the intended behavior your going for is, but one thing I notice is that your methods are adding transformations to the canvas context without resetting afterwards.  That's likely to have unintended consequences, since the transformations can have an effect on drawing unrelated entities.  You can look at the [code in canvas.js](https://github.com/craftyjs/Crafty/blob/deff7307581e69badb10b3ca08c7d0a6675d80c2/src/graphics/canvas.js#L90-L126) for an example of saving and restoring the context state.

**Comment by demarcop** [comment]
Okay, I’ve added the context save/restore and the result did not change.

The intent is to have a black circle with a blue rectangle on it and nothing else.   You’ll notice that the blue rectangle has a yellow background around it.  This does not belong here.  Also playing with the height 80/81 has a dramatic effect on the image much more than 1 pixel.  This should not be the case.

**Comment by starwed** [comment]
I think it's because you're moving the wheel (by setting `cx` and `cy`) within the draw routine.  This invalidates areas of the canvas in an unusual way, which results in the "cut out" region of the wheel around the blue rectangle.  You'll need to do that sort of set up in the init method.
