### ISSUE TITLE
Collision normal bug

### ISSUE THREAD

**Issue by maxencefrenette** [craftyjs/Crafty#137]
There is defintely a bug with SAT collision normal. I don't understand the code enough to fix it.

Blame : 6a950d73026f736cc58fc9e2153e1afb5bd1db13

**Comment by mpetrovic** [comment]
what's the bug?

**Comment by gworley3** [comment]
It's certainly possible that there's a bug because it doesn't detect the side hit by position but by amount of overlap.  This allows the use of SAT without introducing a lot of extra code to keep track of the sides and it's usually right.  What's the bug, though?  Can you show us how to reproduce it?

**Comment by maxencefrenette** [comment]
The normal is wrong.

**Comment by maxencefrenette** [comment]
Oh, sorry, didn't saw your comment, growley3.

First of all, i think that the code you added at line 241 should also be added between line 198 and 199. Second of all, your identation is wrong. And finally, here is a fiddle : http://jsfiddle.net/8Nns4/ .

**Comment by gworley3** [comment]
The return is only at 241 because we need to loop through all the sides of both polygons.  As for indentation, well, I use spaces instead of tabs in my editor so I never noticed it, but if it bothers someone they're welcome to fix it.  Finally, as for the fiddle, the issue appears, without actually stepping through the code, to be that you were expecting a normal of (-1, 0), but got (0, 1) because the amount of overlap for the left side was less than or equal to the overlap for the top side, and the top side was considered first by SAT.

I can't think of a good solution right now.  Overlap works well for guessing which side was hit when you have a small polygon hitting a bigger one, but in this case I see the problem.  The ideal solution is to figure out which side was hit, but the current SAT implementation doesn't really allow it and putting in that feature will technically make the algorithm non SAT.  Not sure what effect a change like this might have on speed, but I'd encourage you to take a look at the problem if it's affecting you.

**Comment by maxencefrenette** [comment]
I dedicate this bugfix to chrome developer tools and its breakpoints :) .

**Comment by louisstow** [comment]
Fixed see commit https://github.com/louisstow/Crafty/commit/7db85a109184fc421d13c3e9c58c4a57bf1b7e1d
