### ISSUE TITLE
Vector and Matrix maths

### ISSUE THREAD

**Issue by louisstow** [craftyjs/Crafty#143]
Would be nice to have some libs to do basic Vector.

**Comment by mpetrovic** [comment]
you have something in mind? Vector is just a set of X and Y values representing change in position, isn't it?

**Comment by louisstow** [comment]
Yep. Should take an object and do stuff like normalization, adding two vectors, dot product etc etc

**Comment by donaldpipowitch** [comment]
I've ported my vector class from AS3 to JavaScript. I will move it to Crafty.math.Vector and upload the code in some minutes.

**Comment by donaldpipowitch** [comment]
I would recommend to use the new vector class in the "2D" component for the _x and _y values so you can easily use the new vector calculations. In addition _z should maybe be renamed to _zIndex (because it is just the "2D" component and not "3D"). That would also make a great testcase to see if the class has some bugs.

**Comment by ahilles107** [comment]
With Crafty.match this issue shoud be closed?
