### ISSUE TITLE
crop does not work during animation

### ISSUE THREAD

**Issue by BlackScorp** [craftyjs/Crafty#178]
Crafty.c("Player",{
init:function(){
this.requires("SpriteAnimation").crop([10,10,20,20])//just example crop
.animate("walk_left", 6, 3, 8) //During animation the Entitie will have full size and not croped size
.animate("walk_right", 9, 3, 11)
.animate("walk_up", 3, 3, 5)
.animate("walk_down", 0, 3, 2)
}
});

**Comment by mpetrovic** [comment]
and what did you expect to happen?

On Wed, Jan 11, 2012 at 4:54 PM, Witali Mik <
reply@reply.github.com

**Comment by BlackScorp** [comment]
i exect that if i crop an entitie, so it will have the size of crop during his exists..

for example, i have a player sprite that is lets say 200x200 size in px. but each sprite image has a margin to other images, so if i want to make a smaller entite than the spritesize, i have to crop it. at start the entitie is smaller than the sprite image size. and after animation it has its base size again..

**Comment by starwed** [comment]
This is basically the same issue as [described here](https://groups.google.com/forum/#!topic/craftyjs/SIG1cJXWW1U/discussion), except with `__trim` instead of `__padding.`   That was fixed in #241.   I think this could be fixed in a parallel way, assuming that cropping should apply to all sprites.  If not it'll be a little bit more complicated, but still fairly straightforward.

Why do we have two different ways of defining essentially the same thing?  Is there some distinction I'm missing?

**Comment by starwed** [comment]
Should be fixed by PR #665?
