### ISSUE TITLE
TweenEnd triggers excessively for a single Tween.

### ISSUE THREAD

**Issue by EzraT** [craftyjs/Crafty#317]
Hello,

TweenEnd triggers for each property inside a single tween, I am assuming it isn't supposed to behave like that.
Happens in both 0.4.9 and the 0.5.0 found on the Modules page.

Example: http://jsfiddle.net/CmrAE/

Personally I think it would be more logical if it would trigger once for each tween, not once for every property inside a tween.

Thanks.

**Comment by mkalam-alami** [comment]
I found this quite counter-intuitive too, but it's actually a good thing, since a tween can be partly overridden by another, [like here](http://jsfiddle.net/XAZHt/3/) (see the last line). In my example, when the first tween is over, **x** won't be at 15 like expected. A `TweenEnd` event for **x** will be triggered instead after 30 frames, with **"x"** passed as the first parameter.

To handle tweens the way you want, name them with an arbitrary property set to true (again, see my example), then look for it in the TweenEnd handler.

**Comment by sorenbs** [comment]
This is a perfect candidate for the upcoming FAQ section. Thanks!
https://groups.google.com/d/msg/craftyjs/efBkhbgvd0E/X-qrk2FVuucJ
