### ISSUE TITLE
the size must be set before require 'Collision' ?

### ISSUE THREAD

**Issue by neekey** [craftyjs/Crafty#321]
I encountered an problem, like;

```
Crafty.c( 'Role', {
    init: function(){

        this.requires( '2D, Canvas, SpriteAnimation, Fourway, Collision, Monster' )
        // set Speed   
        this.fourway( 2 )
        // set size
            .attr({
                w: 32,
                h: 32
            });
    }
...
```

and the 'Monster' is an Sprite predefined, and after that, the entity's behaves like hitting other entity is always weird.

but if I require 'Monster' before 'Collision' or set the size before require 'Collision', every thing goes rigtht

**Comment by sorenbs** [comment]
Thank you. 
Components are initialised in the order specified in the Crafty.e() call. Whe Collision is initialized it just assumes x,y,w,h properties are zero if not set. So this is expected behavior. I have updated the docs to reflect this.

In the next release due tomorrow you can invoke the constructor without parameters to recalculate the hit area based on the new size like this:

Crafty.c( 'Role', {
    init: function(){

```
    this.requires( '2D, Canvas, SpriteAnimation, Fourway, Collision, Monster' )
    // set Speed   
    this.fourway( 2 )
    // set size
        .attr({
            w: 32,
            h: 32
        }).collision();
}
```

...
