### ISSUE TITLE
issues with tinting -- change default color to completely transparent

### ISSUE THREAD

**Issue by shiroto** [craftyjs/Crafty#335]
Hi there, there are some issues with the tint-component:
1. The tint-component must always be added after the sprite. If its not the tint will occur behind the sprite.
2. When you define that your entity needs tint but dont use it, it will be tinted black. I fixed this by turning this:
context.fillStyle = this._color || "rgb(0,0,0)";
into this:
context.fillStyle = this._color || "rgba(0, 0, 0, 0)";
3. Theres no way to tint something thats no rectangle.

**Comment by starwed** [comment]
1. The tinted rectangle is drawn by a triggered "Draw" event; so are "Sprite" components.  The order the "Draw" events are bound in determines which ones on top.  I don't think this is a bug, exactly, since there might be reasons to want one or the other.
2. You're probably right that transparent would be a better default than black.  This should be an easy fix.
3. Same with "Color"; Crafty just doesn't provide many facilities right now for drawing arbitrary shapes.  So probably out of scope of this bug.
