### ISSUE TITLE
addEntityFactory doesn't work in 0.5.1

### ISSUE THREAD

**Issue by ghost** [craftyjs/Crafty#353]
raises error "Uncaught TypeError: Cannot set property 'Projectile' of undefined "

see http://jsfiddle.net/beckyisabunny/Mh4j4/21/

error raised from line 972
this.entityFactories[name] = callback;

**Comment by JesterBlue** [comment]
there are 2 bugs in crafty.js around line 1000 that cause this.
bug 1: Crafty.entityFactories (an array) does not exist.
bug 2: newFactoryEntity tries to reference Crafty.entityTemplates (an array), which does not exist.

//quickfix - run once from your game.js before calling addEntityFactory:
Crafty.extend({
    entityFactories:{},
    newFactoryEntity: function(name) {
        return this.entityFactories[name]();
    }
});

**Comment by cyberbeat** [comment]
when will this be fixed?

**Comment by sbyrnes321** [comment]
https://groups.google.com/forum/#!searchin/craftyjs/addentityfactory/craftyjs/1ESEbI09S7s/ZPRGtg6FgxAJ -- there was a discussion ... Louis suggested deleting the functionality rather than fixing it, although it hasn't happened yet...

Javascript, like every programming language, has a general, easy-to-use method for creating a chunk of reusable code. Just put the code in a function, then call the function whenever you like. addEntityFactory has no special features, all it does is create a chunk of reusable code. So there isn't really any point to it. Just make a Javascript function instead :-P

**Comment by hugeen** [comment]
This functionnality is totally useless

**Comment by starwed** [comment]
The factory was deleted as suggested in #434.
