### ISSUE TITLE
Fourway controls (WASD + arrow keys) don't work in Opera

### ISSUE THREAD

**Issue by darrentorpey** [craftyjs/Crafty#400]
Crafty's Fourway (and possibly Twoway, etc.) component doesn't respond to W, A, S, D, or the arrow keys in Opera.

As an example, see the demo (one of the ones linked from craftyjs.com) for Cron: http://blackscorp.github.com/cron/ 

Here's my full system info:

Version 12.12 
Build 1707 
Platform Mac OS X 
System 10.7.5

**Comment by BlackScorp** [comment]
but there is an old version of Crafty did you tryed newer Crafty version?

**Comment by darrentorpey** [comment]
This is Crafty 0.5.3

**Comment by BlackScorp** [comment]
i mean my demo cron uses 0.4.5

**Comment by darrentorpey** [comment]
Thanks for clarifying, BlackScorp. This problem is definitely present in 0.5.3, but I haven't tried porting your game to 0.5.3.

**Comment by darrentorpey** [comment]
I think I found the problem.

https://github.com/craftyjs/Crafty/blob/master/src/controls.js#L250

"e.key = e.keyCode || e.which" does _not_ change the value of "e.key" in Opera (but does in Chrome, for example).

It's obvious that Opera has a very different handling for "e.key". For example, when you press the "w" key in Opera, e.key is "w" whereas in Chrome, etc. it's the number 87. That line, "e.key = e.keyCode || e.which" is meant to get around this issue but it does not do so because the value of "e.key" is never changed in Opera.

I don't see why that code cannot just set and use a local var in that function to get around this issue.

**Comment by mpetrovic** [comment]
because that event is passed into the handlers, which expect to have all
information regarding the event. We're trying to normalize the value so
Crafty event bindings can be browser agnostic.

What's the real issue, that e.key is read-only in Opera or that e.keyCode
|| e.which is returning something different in different browsers.

**Comment by BlackScorp** [comment]
well mpetrovic if youre right a simple var key = e.keyCode || e.which could fix this problem? and replace all e.key with key in controlls.js?

**Comment by darrentorpey** [comment]
The issue is that in Opera e.key is read-only (and is also defined on "e" when it's passed into keyboardDispatch -- whereas in Chrome/FF "e.key" is not defined and can be set).

**Comment by darrentorpey** [comment]
Was "e.key" meant to be a totally new property that is only used by other Crafty code? If so, then that's our gotcha -- Opera has surprised us and used it in a proprietary way. o_O

If so, then perhaps we could define a different property and perhaps give it a safer name like "cr_key" to avoid this kind of issue in the future. I'm not sure how standard this kind of trick is to use in the first place, though. Do JS libraries often add properties to DOM event objects?

**Comment by BlackScorp** [comment]
@darrentorpey that i ment in my post above, just define a new var and give its the value, replace overall e.key with key , could working maybe

**Comment by mpetrovic** [comment]
Alright then.

Darren, depends on the library. Prototypejs extends a lot of the built-in
JS classes, including events. jQuery creates a wrapper object which is
practically interchangeable with a DOM event.

Witali, just replacing e.key with var key won't work, because we pass e as
an argument of trigger. Any normalization we do needs to be on e or there's
no point in doing it.

jQuery's method is probably the best way for us to handle it. We can have
full control over everything on the event object, document it fully next to
the rest of our documentation and have no confusion as to what gets passed
into event handlers..

**Comment by darrentorpey** [comment]
Alright, I'm looking into how jQuery does this. I was pretty sure they made their own object for these very reasons, so I'd love to emulate that.

**Comment by starwed** [comment]
This was fixed by 401, yes?
