### ISSUE TITLE
Bug due to the fact that this._mbr uses x sometimes and _x other times 

### ISSUE THREAD

**Issue by sbyrnes321** [craftyjs/Crafty#504]
I have a bug where I can create an element where `this._mbr` has the properties `_x`, `_y`, `_w`, `_h`. But then it's used in `isAt`, which expects `x`,`y`,`w`,`h` (no underscores). This is a problem! Mouse events on this element do not get detected.

So far I can't reproduce this in a simple code snippet, nor can I give a more specific chain-of-events that causes this. It happens in my complicated game, and I'll post again if I figure it out more precisely. (Sorry I don't have time for now.) It might have something to do with the fact that my element is rotated. Also, I might have done something wrong in my code! But anyway, what I wrote in the previous paragraph sure looks like a bug in Crafty. :-D

FYI, I'm working off the very latest development branch (f9a66b047117baa2a9d5167f51a7a7bfdd3562f0)

**Comment by starwed** [comment]
> It might have something to do with the fact that my element is rotated. 

If tthe entity isn't rotated, _mbr will be null, and so it will use the object itself instead of _mbr. 

This is fallout from when I tried to fix the issue of the object's _mbr being ignored by some of these functions.  I forgot to change it from `.x` to `._x`.  (The latter is faster even when an MBR isn't present, so another reason to change this.)  At least it's a really easy issue to fix.  :)
