### ISSUE TITLE
Some broken things (bad link in README)

### ISSUE THREAD

**Issue by loicknuchel** [craftyjs/Crafty#524]
Hi,

I'm just started looking at Crafty and I found some broken things...
They are really small things (and don't impact quality of Crafty engine) but they are not really convenient when someone (like me) just jumped into Crafty learning.

InREADME, the getting started link is broken (http://craftyjs.com/tutorial/bananabomber/create-a-game).

In rpg demo, I have an error on line 33 (https://github.com/craftyjs/Crafty/blob/develop/demos/rpg/game.js#L33) : 

```
Uncaught TypeError: Object #<Object> has no method 'playAnimation' rpg.html:41
generateWorld             rpg.html:41
(anonymous function)      rpg.html:82
Crafty.extend.scene       crafty.js:7731
(anonymous function)      rpg.html:68
pro                       crafty.js:9435
```

I ran the game with the lastest release of Crafty (https://github.com/craftyjs/Crafty/releases/tag/0.5.4)
Removing this line, I have other errors on multiples lines : 

```
Uncaught TypeError: Object #<Object> has no method 'pauseAnimation'
```

I didn't try other demos from now but even these errors are minor I think they are really easy to solve and they are very frustrating and difficult to resolve when you just begin using Crafty.

Thanks for paying attention.

**Comment by starwed** [comment]
Thanks for reporting the broken link!

The second issue is caused by mixing branches.  You are attempting to run the demos from the `develop` branch with the 0.5.4 release version of Crafty.  There were changes to "SpriteAnimation" which were not backwards compatible.  If you run those demos with the most recent version of Crafty, they should work; alternatively, the demos in the release branch should work with 0.5.4.  :)

**Comment by loicknuchel** [comment]
Thanks for your quick response and explanation.
It's a little bit weired to have the develop branch as default in github (noobs like me will make mistakes...) but that's ok.
