### ISSUE TITLE
Move npm development dependencies to devDependencies

### ISSUE THREAD

**Issue by potomak** [craftyjs/Crafty#570]
I think all `dependencies` inside `package.json` should be moved to `devDependencies` as they are required to build, test, and manage Crafty code but they're not required by the Cratfy engine itself.

See https://github.com/craftyjs/Crafty/pull/568#issuecomment-26970762

**Comment by starwed** [comment]
I disagree, because the module is _for_ developing crafty.    The npm docs say:

> If someone is planning on downloading and using your module in their program, then they probably don't want or need to download and build the external test or documentation framework that you use.

But Crafty is not (currently) intended to be used as a standalone module, or to be used from other modules.  The _only_ reason to set it up right now is to work on development.  This might change in the future!  But for now I think we should leave things as they are.

**Comment by potomak** [comment]
@starwed even if Crafty is not currently intended to be used as a standalone module it's **always wrong** to list development dependencies as package dependencies.

From the spec (https://npmjs.org/doc/json.html#dependencies):

> Please do not put test harnesses or transpilers in your dependencies hash.

Note: this update wouldn't change the development process on the contrary it could only enhance its overall correctness.

Moreover npm could be used also as a _frontend package manager_, see http://dontkry.com/posts/code/using-npm-on-the-client-side.html

Anyway, this is a really low relevance issue so feel free to close it if you completely disagree with me.

**Comment by kevinsimper** [comment]
I would also think that the current dependencies should be moved to devDependencies, because they are used for development, and are not used in the sourcecode of Crafty.js.

Also it does not make any difference in the workflow. When you do: `npm install` it will also install devDependencies. Only when you env is set to production, then it will not install devDependencies.

**Comment by starwed** [comment]
AFAICT this was resolved at some point -- everything is now in devDependencies.  So closing!
