### ISSUE TITLE
Math Matrix2D invert fails in Chrome

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#677]
There is one test which fails in Chrome, but not in PhantomJS, Safari or Firefox.

It is because of the long decimals:

![image](https://f.cloud.github.com/assets/1126497/1831489/e48efe3a-7391-11e3-842c-9dafea1ee71e.png)
![image](https://f.cloud.github.com/assets/1126497/1831571/82d46682-7394-11e3-9447-a5f1f6adf990.png)

But then i saw in Firefox that the e value switch between -0, and 0;
![image](https://f.cloud.github.com/assets/1126497/1831579/ac1fc752-7394-11e3-93dd-2ce0df162b91.png)
![image](https://f.cloud.github.com/assets/1126497/1831580/b214ca04-7394-11e3-9498-0e909b978423.png)

In safari is there no problems.

**Comment by starwed** [comment]
This is definitely a bug in the test -- I think this came up elsewhere, and I just used a function to round things to 6 decimal places.

**Comment by kevinsimper** [comment]
If you round to 6 decimals, it would still fail because it is different already at the 4th number.

**Comment by starwed** [comment]
> If you round to 6 decimals, it would still fail because it is different already at the 4th number.

Huh, you're right -- that's a surprisingly large difference.

**Comment by starwed** [comment]
The error term is probably so large because rather than test inverting an explicitly defined matrix, it inverts `(new Matrix2D()).scale(2, 3).rotate(Math.PI / 2)`.  

`Math.cos(Math.PI/2)` isn't exactly 0, so this error probably propagates in an unpleasant way.

I'd assume that if we inverted something specified explicitly, we wouldn't get this sort of error.
