### ISSUE TITLE
Drawing Layers & Static GUI

### ISSUE THREAD

**Issue by mucaho** [craftyjs/Crafty#712]
I remember alot of questions/requests for static gui (that doesn't move when the viewport is scrolled). Here is a [recent post](https://groups.google.com/forum/#!topic/craftyjs/v-lsLk7aumk).
A not so performant way is to counter the offset of the viewport by moving the entities in the counter direction (see @starwed 's reply in the post).
Would it be smart to include such a feature in the craftyjs library? (e.g. perhaps something like the [JSFiddle](http://jsfiddle.net/7L3Ps/1/) I posted in a reply).

**Comment by starwed** [comment]
The ideal way to solve this is to refactor Canvas and DOM to support multiple layers.  Then each layer could set a parallax factor that describes how it responds to viewport scroll events.

Having separate layers for the background and UI should help  performance a lot, since they'd be much more static in general than something like Canvas.

There's quite a bit of intermediate work to do before trying that -- lots of hard coded references to `Crafty.canvas` and the like we'd need to switch.  So it might be worth coming up with a stop gap solution for now?

**Comment by mucaho** [comment]
Excellent idea with the layers! Would you open an issue about the layer refactoring and post a bit more information about that? 

I think it might not be worth to come up with temporary solution to static gui, as we have enough work cut out for us already ;)

**Comment by mucaho** [comment]
@mpetrovic was working on [layers](https://github.com/mpetrovic/Crafty/tree/layers). What's the status of that?

**Comment by mpetrovic** [comment]
Stalled. I haven't done any work on it in a long time. If someone wants to
pick up the reins, you can find it here:
https://github.com/mpetrovic/Crafty/tree/layers

**Comment by mucaho** [comment]
According to a recent [forum post](https://groups.google.com/forum/#!topic/craftyjs/XhPiZSU--u8), all entities belonging to the DOM layer will appear above all entities belonging to the Canvas layer.
Reason seems to be the DOM layer init code which sets the div's `style.zIndex = 1`.

I tried setting both layers to the same z-index, but that doesn't have any effect on the ordering of entities with different z-indices.

Hence, it would be nice to provide a method to set a layer's z-index, so that you could have arbitrary render ordering of DOM/Canvas layers. (Hopefully a layer's z-index doesn't interfere with other functionality).

**Comment by starwed** [comment]
Fixed by #1024.
