### ISSUE TITLE
Api-doc makes double p-tags

### ISSUE THREAD

**Issue by kevinsimper** [craftyjs/Crafty#715]
If you do `grunt release`, the api-doc will generate double p-tags.

Do not know why sadly.

I feel like the api-doc.coffee has too tightly coupled with the html, and it makes it hard to figure it out what happends.

Example:

```
<p><p><code>public this .addComponent(String componentList)</code> </p></p>
<p><p><dl></p></p>
```

**Comment by starwed** [comment]
Possibly because the text gets fed through multiple passes of marked?  (A crappy workaround for #710).

> I feel like the api-doc.coffee has too tightly coupled with the html, and it makes it hard to figure it out what happends.

Agreed, that made it a pain to figure out what was going on with 710.    So we should probably have two passes: first pull json data from the docblocks, and then generate the documentation from that data.  (I think you advocated for this idea previously.  :) )

The first step wouldn't be so bad; I'd be willing to tackle it, since I wrote the current parser.

I think there are two paths that make sense for the second step.

### Fully embrace jekyll

Use their templates to generate the documentation.  This has the advantage of being "native" to github. Changing the site layout wouldn't necessarily need the api docs to be recompiled.  But it has the existing disadvantage that we couldn't easily generate the docs offline.

### Use node, generate locally

From poking around, [assemble](http://assemble.io/) seemed the most promising.  Any change to the site layout would require recompiling the docs, but we could easily do so using our existing toolchain.

I guess we could also try a hybrid approach: use something like assemble to preview the docs, but rely on jekyll to compile them on the live site.

**Comment by kevinsimper** [comment]
We should use something else than Jekyll and just generate the full html by ourself.

The problem is now that people do not have jekyll on their computer now, because that would be the easy solution right now, but that is Ruby and would just complicated it even further with another language and dependency.

But the solution would be to still compile html files, but have a local template and one for the website.
