### ISSUE TITLE
Drag doesn't work properly if entity is rotated

### ISSUE THREAD

**Issue by diazluis2007** [craftyjs/Crafty#74]
an entity that is rotated
not rotate the area that used to drag the mouse

if you have an entity such as higher than wide
initially the itienes thus

000000000
000000000
000000000

and broken in this way:

00000
00000
00000
00000
00000

the action of drag with the mouse only funsionara
correctly if the entity is horizontal

the image looks good ..
but still an imaginary horizontal
to regard the action of mouse

**Comment by louisstow** [comment]
It would be much easier if you uploaded a demo or used [JSFiddle](http://jsfiddle.net).

**Comment by diazluis2007** [comment]
Friend is right, sorry

git://github.com/diazluis2007/domino.git
is an example of what is happening.

in /entity/piedra.js

I draw two entities .. must move to see the error
another thing: you must add the file to the root folder crafty.js
I have it on my system as a symbolic link ;)

**Comment by maxencefrenette** [comment]
A clean way to fix this would be to build the drag component on top of the mouse component and make the mouse component compatible with rotation.

Berseker59

**Comment by louisstow** [comment]
Will look into it further.

**Comment by degvalentine** [comment]
The problem lies in the HashMap.key() function - it doesn't take rotation into account when determining which blocks to hash an entity into. The mouseDispatch function uses the HashMap to find mouse entities for the click, but since the entity is in the wrong hash blocks, the click is only detected if it is within the entity's area-map and the incorrect hash block.

Adding the following to HashMap.key will fix it:
if (obj.hasOwnProperty('mbr')) {
  obj = obj.mbr();
}

I'll branch and submit a pull request later.
