### ISSUE TITLE
Differences between transform implementations

### ISSUE THREAD

**Issue by mucaho** [craftyjs/Crafty#744]
`Crafty.DrawManager.renderCanvas()` uses [this line](https://github.com/craftyjs/Crafty/blob/develop/src/drawing.js#L533) to set the transform on the canvas' context:

``` javascript
ctx.setTransform(view._scale, 0, 0, view._scale, Math.round(view._x*view._scale), Math.round(view._y*view._scale) );
```

However,  `DebugLayer.renderScene()` uses [this line](https://github.com/craftyjs/Crafty/blob/develop/src/DebugLayer.js#L359) to set te transform on the canvas' context:

``` javascript
ctx.setTransform(view._scale, 0, 0, view._scale, view._x, view._y);
```

Additionaly `Crafty.DrawManager.renderDom()` uses [these lines](https://github.com/craftyjs/Crafty/blob/develop/src/drawing.js#L640-L642) to set the transform on DOM elements:

``` javascript
style.transform = style[Crafty.support.prefix + "Transform"] = "scale(" + view._scale + ", " + view._scale + ")";
style.left = view.x * view._scale + "px";
style.top = view.y * view._scale + "px";
```

As you can see only the `DrawManager.renderCanvas()` method **rounds the values**.  In the other transforms above and in other occurences of `viewport._scale` (mainly for calculating `viewport._width` or `viewport._height`), the **values are not rounded**.

Is this correct behaviour?

**Comment by starwed** [comment]
Looks like the DebugLayer is simply incorrect, in addition to not rounding -- that should be fixed.

Should the DOM renderer use rounded pixels?  I guess it might as well, for consistency.  In fact, we could add a helper function to the viewport, since currently they all use the same calculation.  (This wasn't true in the past, and I guess might not be true in a webgl renderer, so maybe it's not worth it.)
