### ISSUE TITLE
Crafty.map.search revision

### ISSUE THREAD

**Issue by kanecko** [craftyjs/Crafty#783]
May I suggest a few usability changes to `Crafty.map.search`?
1. Allow negative width/height. Canvas allows it as well, and it goes nicely with implementing a standard RTS multiple unit selection rectangle.
2. The function uses both `_x` and `x`, but it's not well documented which one is for what. Can there be only `x`?
3. Would it be sensible to change the function signature to `x, y, w, h, filter`?
4. More documentation needed on crafty's website for the whole `Crafty.map` namespace.

**Comment by starwed** [comment]
> Allow negative width/height. Canvas allows it as well, and it goes nicely with implementing a standard RTS multiple unit selection rectangle.

I'll look into that -- it shouldn't be too hard to do.

> Would it be sensible to change the function signature to x, y, w, h, filter?

Another alternative is to change it to be `x1, y1, x2, y2`.  (Coordinates of top-left/bottom-right points, since that's actually what uses internally.)

> More documentation needed on crafty's website for the whole Crafty.map namespace.

Hmm, for some reason a lot of existing docs for `.map` aren't being parsed by our doc generator.

> The function uses both _x and x, but it's not well documented which one is for what. Can there be only x?

On entities, `x` is just a setter/getter for `_x`.  The function itself looks at `_x` because that's faster.  (Then, objects like the MBR use `_x` for consistency.)

**Comment by kanecko** [comment]
> Another alternative is to change it to be x1, y1, x2, y2. (Coordinates of top-left/bottom-right points, since that's actually what uses internally.)

Sounds good to me.

> On entities, x is just a setter/getter for _x. The function itself looks at _x because that's faster. (Then, objects like the MBR use _x for consistency.)

Good to know, thanks!

**Comment by kevinsimper** [comment]
Map is just a instance of Hashmap, and therefore there is not documentation about map.

> Hmm, for some reason a lot of existing docs for .map aren't being parsed by our doc generator.

We talked about it a bit here :-)
https://github.com/craftyjs/Crafty/pull/721#issuecomment-34616656

I think we shoud rename `.map` to `.HashMap` or wise versa, or that would help the docs generator.

**Comment by starwed** [comment]
I'm going to go ahead and close this, since the assumption that we're dealing with an object with `_x`, `_y`, `_w` and `_h` is pretty pervasive throughout the map code.

I could imagine rewriting the whole thing to take arguments in a different way, but that would only make sense in the face of some other large changes. 

The documentation thing is still a problem, but that's already tracked in our bugs for revamping the docs.  :)
