### ISSUE TITLE
Safari 5.1.0 error when checking for audio support

### ISSUE THREAD

**Issue by kanecko** [craftyjs/Crafty#788]
I've been testing my game to see which browsers support it (Crafty 0.6.2). If the aforementioned browser is officially not supported, ignore me :)

When trying Safari 5.1.0, my game crashed with: `TypeError: 'undefined' is not a function (evaluating 'audio.canPlayType(this.codecs[i])')`

The line in question is `canplay = audio.canPlayType(this.codecs[i]);` in the `_canPlay` function.

Note 1: I don't use the audio facilities, nor do I intend to.
Note 2: I've disabled the audio stuff and the game is working fine, albeit a bit stuttery.

**Comment by kevinsimper** [comment]
Hi @kanecko 

Do you have some code where I can see it? Did you fix it yourself?

If it is an error that is not difficult to look out for we should do that :)

**Comment by kanecko** [comment]
Sorry for the delay. 
I have no code as I've switched to another library, but even the barebone Crafty app will throw the same error, so it should be easy to test.

**Comment by starwed** [comment]
I'd guess that this was a problem for the windows version of Safari, which simply doesn't support `audio` elements if the right codecs/plugins aren't installed.

If that was the case, then the real issue is that our test for audio support is wrong.  We should try creating an audio element and checking that is has the `canPlayType` method -- that's a standard check, and will definitely fix this bug!
