### ISSUE TITLE
Collision polygon moves on resize

### ISSUE THREAD

**Issue by austinh** [craftyjs/Crafty#791]
I need to resize an entity. I have 2 collision hitboxes per size, one for the resized entity and one for the larger original sized entity. Whenever I resize the entity down the collision hitbox seems to move away.

http://jsfiddle.net/ysDtQ/86/

Look at what I did here! The more .collision is called the more it moves away. I can't figure out why this happens. Should i be able to switch the collision hitbox without stuff moving? I can't find anything in the source code that would cause this to happen except maybe some on("Resize") math error?

**Comment by starwed** [comment]
Ah, I don't think it's anything to do with the resizing.  It's to do with removing and then adding a collision polygon.

The `.collision` method takes a polygon whose coordinates are relative to the entities position.  (So `[0, 0]` means the upper left corner.) But once the polygon is attached to the entity, it's coordinates are translated to match the entities.  If you try to reattach it at a later point, it is again translated based on the entities x/y coordinates, which is why the error accumulates every time you make the switch.

So the basic issue is that the entity will actually change the coordinates of smallCollision and largeCollision.   (And while I haven't thought about it in depth, I believe this is necessary for performance reasons.)  Thus, they can't be reused at a later point.  This should probably be added to the documentation!

**Comment by austinh** [comment]
Alright. Is there anyway around this relative position? I can't quite figure out how/where this collision relative math is taking place. Although perhaps there's a crafty (pun intended) way to get around this.

**Comment by starwed** [comment]
This is basically addressed by #858, so closing.  :)
