### ISSUE TITLE
Check if Audio object exists for IE

### ISSUE THREAD

**Issue by louisstow** [craftyjs/Crafty#8]
IE will throw an error when trying to instance Audio.

**Comment by joshtynjala** [comment]
In case you weren't aware, IE9 beta seems to support `document.createElement("audio")`, but not `new Audio()`. However, IE9 platform preview 7, which is a newer build than the beta, supports both.

**Comment by louisstow** [comment]
Hmm so would you recommend sticking with `Audio()`? Do any other browsers only support the tag?

**Comment by joshtynjala** [comment]
Since it's mostly only developers testing IE9, you're probably safe sticking with what you have right now. When IE9 is released, the devs will all upgrade, and the vast majority of non-developers will never have installed the beta, so they'll be fine too.

In my testing, the other browsers handled the constructor fine.

**Comment by louisstow** [comment]
Added better support which will check for features on startup. IE silently degrades.
