### ISSUE TITLE
Transparent parts in PNG files doen't render properly

### ISSUE THREAD

**Issue by husathap** [craftyjs/Crafty#802]
I have tried to load a png file with a transparent part and uses it in a sprite. When I use the sprite in an entity, the transparent part doesn't render properly. Instead of having transparent part, I get white part instead.

I am using the latest stable release of Crafty.

**Comment by kevinsimper** [comment]
Sounds like a bug. Do you have a place where you can show it?

**Comment by husathap** [comment]
I don’t have a github for the code yet, I will set it up as soon as possible.

From: Kevin Simper
Sent: ‎Thursday‎, ‎July‎ ‎17‎, ‎2014 ‎12‎:‎30‎ ‎AM
To: craftyjs/Crafty
Cc: Hubert Hu

Sounds like a bug. Do you have a place where you can show it?

**Comment by husathap** [comment]
I have put the code where it can be viewed as promised: https://onedrive.live.com/redir?resid=BD4B265F26152DB8!16599&authkey=!AIPP8WLJ77DTMKs&ithint=file%2c.zip

From: Kevin Simper
Sent: ‎Thursday‎, ‎July‎ ‎17‎, ‎2014 ‎12‎:‎30‎ ‎AM
To: craftyjs/Crafty
Cc: Hubert Hu

Sounds like a bug. Do you have a place where you can show it?

**Comment by kevinsimper** [comment]
I look at the code and that is because you are using the Color component and setting the color to white  in player.js.

There is a bug however as you properly seen where a background would be drawn ('black'), if no color has been set, but that has been fixed in the code and will be published soon!

So quickfix is to not have Color component in the player component undtil you need a color background :)
