### ISSUE TITLE
TweenEnd is fired multiple times

### ISSUE THREAD

**Issue by heniotierra** [craftyjs/Crafty#824]
I noticed this long ago, but always find a way to circumvent the problem. What the title says, in some situations TweenEnd is fired multiple (sometimes three or four) times, but for me it's obvious it should fire only once. Because of this issue, ugly workarounds are needed.
In most cases using `this.one("TweenEnd",function(){ [...] })` avoids the problem, but in some other situations this won't help so much, forcing me to use `delay` to execute that callback function.
Oh, by the way, I remember the delay bug I helped solve some time ago was caused by the enterframe event being fired a few times after pausing... maybe there is a relation there? Could it be that the function that triggers the tween steps (on enterframe?) is still bound even after tween "ended"? Or something like that... (I don't fully understand Tween inner workings yet)

**Comment by kevinsimper** [comment]
Do you have some code where I can see it happens? :)

**Comment by heniotierra** [comment]
This is a bit tricky to replicate, but, here's my try. The first link portraying the problem (more or less) and the second one with a workaround. "More or less" because in jsfiddle the engine goes crazy and stops working, but depending on the situation it may keep working, however the tween will be completely smugged up.

Intended behaviour: the box must keep going on and then coming back.
Problem: http://jsfiddle.net/heniot/kkap38t4/17/
Workaround: http://jsfiddle.net/heniot/kkap38t4/18/ (smells like balls)

The first fiddle does not work because the function `box.moov` rebinds "TweenEnd" immediately, and it happens that more "TweenEnds" are fired thereafter yet from the previous `box.moov` call, making `box.moov` be called again and again and again (two to four times beyond normal - which is once). In Firefox this fiddle freezes for me and if I choose to debug the thing it will point to Crafty's line 4489 -> 
`current = hdl[this[0]];` .

The second fiddle works because by the time the event "TweenEnd" is bound, those events that misfired are through.

**Comment by starwed** [comment]
"TweenEnd" fires only once per tween -- you can see this if you bind to the event outside of `moov`.
With [this modified example](http://jsfiddle.net/kkap38t4/20/), you can see that an event bound to TweenEnd only fires once (at first), but `moov` fires 20 times.  (Of course, once each of those 20 bound tweens then end, you see an additional 20 of that extra event fires.  I think that might indicate a different problem, since they should be deleting each other?)

 I _think_ this is actually a nasty interaction between Tween and how our event system works.
1. "TweenEnd" fires.  Crafty starts iterating through the list of events bound to "TweenEnd".
2. That triggers the `moov` function, which binds a new event to "TweenEnd".
3. `moov` returns, Crafty continues the iteration through the bound events, and discovers the newly bound event.  It's immediately triggered.

This seems like a somewhat major flaw, and I'm surprised it hasn't come up before.  Maybe we changed something about the iteration recently?  Or perhaps I don't actually understand what's going on.  :)

**Comment by heniotierra** [comment]
Hum... You might be right, but I saw this happening in other situations where a message would be logged many times when bound to TweenEnd. However, this scenario seems to be more difficult to replicate, don't know why. The code was very simple, something like:

```
entity.tween({ x: toX, y: toY })
    .bind('TweenEnd', function(){ 
        console.log("Tween finished"); 
        // do some stuff
    }) 
```

The code in this case was not meant to be repeated (and that was the only time `.tween` was used in this `entity`), unlike the example in the fiddle, thus the bound function should only fire once anyway. However as I said, "Tween finished" would be logged many times (three times in the specific situation that comes to my mind), and the "stuff" would be executed many times too. Ofc, using `.one` instead of `.bind` would avoid the problem.

> Maybe we changed something about the iteration recently?

I think I first noticed this issue with Crafty 0.5.4, but it might exist prior to that version?

**Comment by starwed** [comment]
@heniotierra  Well, in older versions of Crafty we fired "TweenEnd" once per property, instead of once per group.  So that might have been what you were previously seeing.

This particular issue arose when we [changed](https://github.com/craftyjs/Crafty/pull/500/files#diff-7eb52b366866677666470e019283c8eaR654) things to prevent the opposite issue -- removing an event mid-iteration caused problems.  This was part of the `one()` and `uniqueBind()` PR, #500.

There's a fair amount of conversation in the PR, but we totally missed this particular bug!  :)

The least intrusive fix would be to cache `callbacks.length`, and decrement it when we delete an event.

**Comment by starwed** [comment]
I have a fix ready for this, but since it ever so slightly changes how event processing works I want to play around with it a bit more.

(The basic idea is to cache callbacks.length as noted above, and only splice an item out of the callback array if the current event wasn't triggered "within" the same event type.)

**Comment by heniotierra** [comment]
> Well, in older versions of Crafty we fired "TweenEnd" once per property, instead of once per group. So that might have been what you were previously seeing.

Uh, oh! Didn't know about that.

And WOW, it's fantastic that you found a solution so quickly! Nice! :D

**Comment by heniotierra** [comment]
>  in older versions of Crafty we fired "TweenEnd" once per property, instead of once per group

That was most probably the case then.
