### ISSUE TITLE
Add a command flag to enable running in background

### ISSUE THREAD

**Issue by garside** [craftyjs/Crafty#855]
I'm using Crafty to create an "idle run" game. Would it be possible to add some kind of "runInBackground" flag or some other idiom to actually allow the frames/drawing to happen even if nobody is looking at the tab actively?

**Comment by kevzettler** [comment]
This is a larger discussion of decoupling the rendering logic from the engine logic. This would also be valuable to allow Crafty to run in a node.js server environment

**Comment by garside** [comment]
That would also be really nice!

Honestly it might be worth it to add support for web-workers (though I dunno if that works so well in node.js) and allow binding to a new "FixedFrame" event or something?

**Comment by starwed** [comment]
Currently we use `requestAnimationFrame` to drive the game loop, and browsers fire that only occasionally when the tab doesn't have focus.  But, they also throttle `setInterval` and `setTimeout`, so allowing you to switch to them won't necessarily help.   I think this is just a straight up limit on how the event loop of browsers works, but if you can find away around it, I'd definitely be open to adding that functionality as an option!

I think your particular use case can be satisfied by [changing the mode of the gameloop](http://craftyjs.com/api/Crafty-timer.html#Crafty-timer.steptype), though: `Crafty.timer.stepType("variable", 60000)` would set the maximum time step to one minute.  Then, so long as your logic works off the time step rather than just incrementing each frame, everything should be ok.

Another option would be to detect when the tab has lost focus, and to use `Crafty.timer.simulateFrame()` to catch up for missing time.

**Comment by starwed** [comment]
Closing, since it doesn't seem technically possible to run the gameloop (at the normal speed) while the tab is inactive.
