### ISSUE TITLE
Use single canvas for all particle effects

### ISSUE THREAD

**Issue by mucaho** [craftyjs/Crafty#924]
From [forum post](https://groups.google.com/forum/#!topic/craftyjs/yaur0zuVQO8)
Problem

> everytime i draw a particle effect, another Canvas element is created on my page

Possible solution

> I'm pretty sure it could be changed to use the existing Canvas instead -- I don't think that would speed up rendering any, but it would probably improve performance in the case where you're often creating/destroying particle effects.  (I think it would also let us remove some special case code in Particles that deals with viewport transformations, because it could then just be handled the same way other Canvas entities are.  Oh, and you could layer particle effects z-values correctly with the rest of a scene.)

Possibly implement together with #847.

**Comment by starwed** [comment]
I actually started poking at this about half an hour ago! 

My current strategy is to just use the regular canvas rendering techniques for the particle effects.  That could create a performance hit[1], but that'll be negated if we allow multiple canvas layers.

It also means all of the code handling viewport transformations can be removed, since the canvas layer will handle it with no issues.
1. If particles are spraying all over the place, it'll trigger any overlapping entities on the same canvas to be redrawn.

**Comment by mucaho** [comment]
fixed by #1132
