### ISSUE TITLE
BUG: mouse event for DOM component if the position value is not absolute

### ISSUE THREAD

**Issue by neekey** [craftyjs/Crafty#95]
if the positon attribute is not absolute of an entity with 'DOM' component, the bind method doesn't work well

see code: http://jsfiddle.net/neekey/yFQz2/13/
the demo does work , but the source code of Crafty is quite clear , hope to fix this bug

mouseDispatch: function(e) {

```
            - - - - - - - - - - - - - - - - -

    for(l=q.length;i<l;++i) {
        //check if has mouse component
        if(!q[i].has("Mouse")) continue;

        var current = q[i],
            flag = false;

        if(current.map) {
            if(current.map.containsPoint(x, y)) {
                flag = true;
            }
        } 

                   //@@@@ if postion is not absolute, this will always be true, wherever the entity is

                   else if(current.isAt(x, y)) flag = true;

        if(flag && (current._z >= maxz || maxz === -1)) {
            //if the Z is the same, select the closest GUID
            if(current._z === maxz && current[0] < closest[0]) {
                continue;
            }
            maxz = current._z
            closest = current;
        }
    }
```

---

**Comment by louisstow** [comment]
I think the position should always be `absolute` for DOM entities. I will wait until other devs weigh in on the issue.

**Comment by mpetrovic** [comment]
For entities, yes. However, I think a system for building HTML inside entities would be extremely helpful for GUI building. One of the draws of this platform is that layout can be generated by the browser automatically, rather than by hand. That was something that annoyed me about working with Flash. 
If we can build game menus by just generating a list and then styling it, that would make everyone's life easier, I think. And if we have this system, it'll need to catch mouse events that aren't necessarily in the entity.
