### ISSUE TITLE
Allow for horizontal/vertical mirroring

### ISSUE THREAD

**Issue by rcfox** [craftyjs/Crafty#96]
In sprite sets, it's common to only animate characters walking left or right, and then mirroring that to get the opposite direction. Vertical mirroring would be useful for over-head animations.

Could support for this be added to Crafty?

Thanks.

**Comment by louisstow** [comment]
Good idea. Will look into that, thanks.

**Comment by omatase** [comment]
I second the need for this

**Comment by mpetrovic** [comment]
This can be done with CSS3 transform, although IE8 and lower will need a filter. I'll work on this over the weekend.

**Comment by mpetrovic** [comment]
Calling for feedback before I go implementing anything. Here's my proposed API: 

<pre>Crafty.e('Sprite').flip('y')</pre>


It's very dumb. It takes the axis you want to flip on, and then does so. Management of whether to flip or not needs to be handled by the application, since the engine has no way of knowing which way a sprite's contents are facing.

**Comment by louisstow** [comment]
Sounds fine.

Could just do .flipY() and .flipX(). Shorter code.

**Comment by omatase** [comment]
@mpetrovic: I like it but I think .flipY() and .flipX() would be a little better though too.

**Comment by mpetrovic** [comment]
The people have spoken. 

I did some research on implementing this. For most browsers it's relatively trivial. For IE8, it's significantly more work. The only way to do it in IE8 is to use the the Matrix filter, which would mean implementing Matrix math. I could do that myself, or I could use a library to abstract it all away. 

So the question is this:
What's our stance on including libraries? I don't mean big ones like jQuery, just smaller single-use libraries, like Matrix handling.

**Comment by louisstow** [comment]
Depends on their license I guess. I'm ok with it as long as it's no huuuge and we should be able to use it in other places. The rotation implementation currently uses matricies so if you could find a way to make them work together that would be great.

**Comment by rcfox** [comment]
If this is the Matrix filter you're referring to (http://msdn.microsoft.com/en-us/library/ms533014(v=vs.85).aspx) then it looks pretty easy. They even say in the remarks how to do vertical and horizontal flips.

As a side note, you can reflect across an arbitrary line with a general reflection matrix: http://en.wikipedia.org/wiki/Coordinate_rotations_and_reflections

**Comment by louisstow** [comment]
But if you need to merge matrices then it gets difficult. Which would be the
case for rotation and flip.

**Comment by rcfox** [comment]
Okay, so for each rotation/flip, you store a transformation matrix in an ordered list. Whenever the filter needs to be updated, multiply the matrices in (reverse?) order. 2x2 matrix multiplication is simple.

**Comment by louisstow** [comment]
Good point. Even still a matrix library might be helpful to other users.
Just have it under the Crafty namespace.

**Comment by mpetrovic** [comment]
If it was just doing flips, I wouldn't be that concerned about a library. But because we need flips, rotation AND arbitrary scaling all in this one matrix, I was concerned about needing a library or having to implement it myself. 

Why would we keep a list of every transformation matrix? I was just going to keep one matrix that represented every transform on an entity, and then do maths on it with the change transformation to get the new one.

**Comment by rcfox** [comment]
I thought it might be useful to be able to remove one of the transformations without affecting the others. I've never designed stuff like this though, so feel free to ignore me. :P

In terms of rotations, reflections and scaling (and shearing), the math involved is very simple. The key is to do each operation individually. That is: apply a rotation, and then a reflection, and then a scaling. If you do it like this, you get the same result as if you had made a rotation-reflection-scaling matrix. (The only thing to look out for is if you're doing these transformations with respect to a different frame of reference. In that case, you can still do each operation individually, but the order of the operations matters.)

Also, I disagree with having a matrix library sitting around for general use. If a JS matrix library already exists, people should just use that. There's no point in bloating the code needlessly.

**Comment by mpetrovic** [comment]
I see your point about removing individual transforms, and that may be something to keep in mind for builder. For the actual engine, though, I'm not seeing a benefit. Compute a total matrix and any additional transforms are layered on top of that. Any transforms people do need to be relative, rather than absolute. (rotate(45) -> rotate(-45) to undo rather than rotate(45)->rotate(0))

I'm not sure what you mean in the last sentence. We wouldn't be writing a matrix library ourselves. I wouldn't be anyway. I'd just be using a library that's already out there.

**Comment by louisstow** [comment]
Implemented it with `scaleX(-1)`. Use `.flipX = true;`
