### ISSUE TITLE
Rendering issue with flipped+rotated child canvas entities

### ISSUE THREAD

**Issue by FallSe7en** [craftyjs/Crafty#962]
Hi,

I've noticed a re-rendering issue when you attach a flipped+rotated canvas child entity to a parent entity. Not sure if I'm doing something wrong or if it's a legit bug, but here is a small demo: http://pastie.org/private/bsq9ixp6fkqzuxylmr70g

Let me know if there is any other information I could provide that might be helpful.

**Comment by starwed** [comment]
Thanks for the report!  There was a bug with setting the canvas context -- it could produce some really weird graphical glitches when entities were both flipped and rotated, and I'd assume that's what you're seeing.

Luckily, it was fixed in the develop branch by #839.  You can test the most recent [beta build](https://github.com/craftyjs/Crafty/releases) to make sure that the issue is gone.  (But make note of the breaking changes, in case they affect your game.)

**Comment by FallSe7en** [comment]
Just checked it out and it does indeed fix the issue for me. Thanks!
