### ISSUE TITLE
WebGL "Number of entities exceeds maximum limit." not clear

### ISSUE THREAD

**Issue by matthijsgroen** [craftyjs/Crafty#977]
There is no clear cause what triggers the `"Number of entities exceeds maximum limit."`.

After looking in the code, https://github.com/craftyjs/Crafty/blob/develop/src/graphics/webgl.js#L68

I learned that this limit is somehow 1024.

But when my game halts with this error, the console returns the following:

`Crafty('*').length => 127`
`Crafty('WebGL').length => 90`

How is this limit reached?

I do create entities which I destroy later on. Does destroying a WebGL entitiy clear it from this limit?

**Comment by 200sc** [comment]
You're right, It looks like deleting a WebGL entity doesn't remove it from WebGL's internal list.

https://jsfiddle.net/mqjanudn/

This code demonstrates that. You can uncomment the unregister entity section to get it to function properly.  

Sprites already have this code, and so they should be expected to adjust to needing to unregister themselves.
(https://github.com/craftyjs/Crafty/blob/develop/src/graphics/sprite.js#L203)

``` javascript
remove: function(){
        this.unbind("Draw", this._drawSprite);
        // Webgl components need to be removed from their gl program
        if (this.program) {
            this.program.unregisterEntity(this);
        }
    },
```

We could probably modify WebGL's remove itself to include this line:
(https://github.com/craftyjs/Crafty/blob/develop/src/graphics/webgl.js#L218)

``` javascript
    remove: function(){
        this._changed = true;
        this.unbind(this._glChange);
        this.program.unregisterEntity(this); // NEW
    },
```

With that change locally, the fiddle runs  without a crash, although it might necessitate removing that same logic from Sprite so that it was only being unregistered in one place.

**Comment by starwed** [comment]
Yeah, definitely is a bug with the existing implementation.  I'll try to fix this later and push a minor release.  (Anyone should feel free to submit a PR for it, though!)

**Comment by matthijsgroen** [comment]
I'll try to create a PR for it
